[package]
name = "letronna"
version = "0.1.0-alpha.1"
description = "A small native desktop agent built with GPUI"
license = "MIT"
repository = "https://github.com/wweziza/letronna"
edition = "2024"

[dependencies]
gpui = "=0.2.2"
gpui-component = "=0.5.1"
async-channel = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }

discord-rich-presence = "1"

[target.'cfg(windows)'.dependencies]
tray-icon = "0.25"
raw-window-handle = "0.6"
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_System_Registry", "Win32_System_Threading", "Win32_Security"] }

[build-dependencies]
embed-resource = "3"

[profile.release]
opt-level = 2
lto = "thin"
strip = true

[profile.dev]
debug = 0
